### ISSUE TITLE
Your code doesn't match the course

### ISSUE THREAD

**Issue by coryhouse** [volkancakil/pluralsight-redux#1]
There's no need to use object assign like you did here: https://github.com/volkancakil/pluralsight-redux/blob/master/src/components/common/LoadingDots.js#L8

In the course I'm simply doing this:

`return <span {...this.props}>{text}&nbsp;</span>;`

So I'd just change https://github.com/volkancakil/pluralsight-redux/blob/master/src/components/common/LoadingDots.js#L8 to this:

`return <span {...this.props}>{text}&nbsp;</span>;`

**Comment by volkancakil** [comment]
@coryhouse We are mutating our loadingDots component's 'dots' prop is here. https://github.com/volkancakil/pluralsight-redux/blob/master/src/components/common/LoadingDots.js#L25 

I think it is necessary because what i do on the line 8  

![adsiz](https://cloud.githubusercontent.com/assets/2703634/18811315/a3d8d6d8-82b4-11e6-9320-3c97f4f934b1.jpg)

**Comment by volkancakil** [comment]
get that warning when i used course version of loadingDots 
take a look
![adsiz](https://cloud.githubusercontent.com/assets/2703634/18811786/82d1cfba-82c5-11e6-8fa8-39fb8643394b.jpg)

**Comment by volkancakil** [comment]
@coryhouse I get that warning when i used course version of loadingDots 
take a look
![adsiz](https://cloud.githubusercontent.com/assets/2703634/18811790/e9d01c62-82c5-11e6-8779-fa22a5d122b0.jpg)

**Comment by volkancakil** [comment]
@coryhouse This warning is meanfull right now. I was update project dependecies and using "react": "15.3.2" and i guess my solution is correct.

[https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b
](url)
> For anyone who is curious/wondering why this new warning exists...
> 
> Historically, React has maintained a whitelist of all valid DOM attributes, and we would strip unrecognized attributes. This approach has a couple major downsides:
> 
> Performance: It means we must do a check for every prop on every DOM element, to sanity check that the prop is valid, and strip the prop if it is not legal. This is silly, because the majority of elements are completely safe (no illegal attributes) and thus the checks are just wasted CPU cycles.
> The old technique forced us to maintain a huge whitelist of all possible DOM attributes. This is a pain to maintain, but more importantly, if we accidentally miss one or browser vendors add a new one, it means that prop can't be used until we update our whitelist
> The old technique is less flexible because it is impossible to render a non-standard attribute. While rendering non-standard attributes is not recommended (you should use a data- attribute instead), sometimes there are situations/frameworks that require it. It sucks that React previously couldn't support it.
